### ISSUE TITLE
DHIS 2 API for pulling Period Based on Data Set Name selected

### ISSUE THREAD

**Issue by mountainclimbing** [dhis2/dhis2-android-sdk#1304]
Do we have an API for dynamically pulling the Period based on the Data Set selected?

Currently am using the following API for pulling the DataSets
https://play.dhis2.org/2.34.0/api/dataSets

For pulling the Data Element Names based on the DataSet
https://play.dhis2.org/2.34.0/api/dataElements.json?filter=dataSetElements.dataSet.id:eq:OsPTWNqq26W

Do we have something like below for pulling Periods?
https://play.dhis2.org/2.34.0/api/period.json?filter=period.dataSet.id:eq:OsPTWNqq26W

**Comment by vgarciabnz** [comment]
Follow up in the community https://community.dhis2.org/t/dhis-2-api-for-pulling-period-based-on-data-set-name-selected/39653
