### ISSUE TITLE
Visibility of model fields.

### ISSUE THREAD

**Issue by Araz-Abishov** [dhis2/dhis2-android-sdk#30]
Right now all fields in models are private. DbFlow knows how to handle those fields by discovering them through getters/setters combination. Recently, I have noticed that this mechanism does not work for all fields in models. Some of them are not recognized for unknown reason (It seems to be DbFlow issue), for example shortName in DataElement. 

In order to solve it, I propose to make model fields to be package private. It means DbFlow will be able to recognize them easily (without using getters/setters combo), and at the same time, the fields won't be accessible directly through object properties outside of the models package. 

Also, it will be good to explicitly specify column names like: @Column(name = "shortName"). In future, it can save us time if we will decide to change field name without making database migrations.

**Comment by simernes** [comment]
Yes that seems like a good idea. Especially if the bugs you mention are prevalent

**Comment by simernes** [comment]
@Araz-Abishov this is done now right?

**Comment by Araz-Abishov** [comment]
That's right. The fix is available in master branch.
