### ISSUE TITLE
Ask user to remove data when skip logic hides data elements

### ISSUE THREAD

**Issue by erlingfjelstad** [dhis2/dhis2-android-sdk#34]
If skip logic is applied to a data element and it hides other data elements that has values, the user should be asked if he wants to clear(set to "") those data element values.

**Comment by Bekkalizer** [comment]
In Tracker Capture and Event Capture the clearing happens automatically, but gives a warning message if the newly hidden fields contained a value that was cleared. A generic user message, or the "Content" property of the programRuleAction if this field is containing a text. 

So we should keep the implementation the same in both places I think, but how it all should work is always up for discussion :)

Markus

**Comment by simernes** [comment]
So does that mean that the values can't be restored. For example if you clicked the wrong option in an option set, and actually didn't intend to trigger something to be hidden?
