### ISSUE TITLE
Implement displaying of Description for data elements in DataEntryFragment

### ISSUE THREAD

**Issue by simernes** [dhis2/dhis2-android-sdk#36]
It is possible add a description to data elements. For example this could be an explanation to health workers on being more exact in the data to enter, or something else.

Implement some sort of pop up bubble or toggle to show the description of a data element.
Default should be hidden, but perhaps add an "info" button somewhere that can be pressed.

**Comment by Bekkalizer** [comment]
You can also take a look at how this is implemented in tracker capture: a clickable (i) icon to open the description text.

Markus
