### ISSUE TITLE
Getting option attributevalue is not possible?

### ISSUE THREAD

**Issue by ivanarrizabalaga** [dhis2/dhis2-android-sdk#60]
I'm trying to prepare a PR so you can get option attribute values via your sdk but I'm not able to find the right fields param to make it work.

I started from your current call:

**Current sdk call to get optionset and options details**:
    https://<<my_dhis_server>>/api/optionSets?paging=false&fields=_,options[_]  

which returns:

``` xml
        <metadata xmlns="http://dhis2.org/schema/dxf/2.0">
            <optionSets>
                <optionSet created="2016-02-08T12:55:09.940+0000" lastUpdated="2016-02-09T14:29:43.342+0000" name="DB - DE Type" id="akyRgB3QVhB">
                    <displayName>DB - DE Type</displayName>
                    ...
                    <options>
                        <option code="92" created="2016-02-08T20:01:29.000+0000" lastUpdated="2016-02-09T14:29:42.842+0000" name="QUESTION" id="OUuryREhgMK">
                            <displayName>QUESTION</displayName>
                            <externalAccess>false</externalAccess>
                            <userGroupAccesses/>
                            <attributeValues/>
                        </option>
                        <option code="93" created="2016-02-08T20:01:29.000+0000" lastUpdated="2016-02-09T14:29:42.096+0000" name="COMPOSITE_SCORE" id="mznbSsWOOpk">
                            <displayName>COMPOSITE_SCORE</displayName>
                            <externalAccess>false</externalAccess>
                            <userGroupAccesses/>
                            <attributeValues/>
                        </option>
```

Then I checked that the path affecting attributeValues is the right one
**Checking path to attributeValues is the right one by filtering that field out (it works)**:
    https://<<my_dhis_server>>/api/optionSets?paging=false&fields=_,options[_,!attributeValues]

```
You get the same xml without the attributeValues entry.
```

And finally try to the get the values associated to my options without any success..

**Asking all from attributeValues   in different manners**:

https://<<my_dhis_server>>/api/optionSets?paging=false&fields=_,options[_,attributeValues[*]]

https://<<my_dhis_server>>/api/optionSets?paging=false&fields=_,options[_,attributeValues[_,attribute[_]]]

https://<<my_dhis_server>>/api/optionSets?paging=false&fields=_,options[_,attributeValues[*,attribute[name,displayName,created,lastUpdated,access,id,valueType,code]]]

https://<<my_dhis_server>>/api/optionSets?paging=false&fields=_,options[_,option[_,attributeValues[_]]]

None of these attempts return the info of the attributeValues, any clue?

Thanks!

**Comment by mortenoh** [comment]
Hi

Something like this should work:
/api/optionSets.json?fields=*,options[*,attributeValues[*,attribute[*]]],attributeValues[*,attribute[*]]

(also gets attribute values of option sets themselves)

On Tue, Feb 23, 2016 at 1:30 AM, Ivan Arrizabalaga Getino <
notifications@github.com> wrote:

> I'm trying to prepare a PR so you can get option attribute values via your
> sdk but I'm not able to find the right fields param to make it work.
>
> I started from your current call:
>
> *Current sdk call to get optionset and options details*:
> https://<>/api/optionSets?paging=false&fields=*,options[*]
>
> which returns:
>
>         <metadata xmlns="http://dhis2.org/schema/dxf/2.0">
>             <optionSets>
>                 <optionSet created="2016-02-08T12:55:09.940+0000" lastUpdated="2016-02-09T14:29:43.342+0000" name="DB - DE Type" id="akyRgB3QVhB">
>                     <displayName>DB - DE Type</displayName>
>                     ...
>                     <options>
>                         <option code="92" created="2016-02-08T20:01:29.000+0000" lastUpdated="2016-02-09T14:29:42.842+0000" name="QUESTION" id="OUuryREhgMK">
>                             <displayName>QUESTION</displayName>
>                             <externalAccess>false</externalAccess>
>                             <userGroupAccesses/>
>                             <attributeValues/>
>                         </option>
>                         <option code="93" created="2016-02-08T20:01:29.000+0000" lastUpdated="2016-02-09T14:29:42.096+0000" name="COMPOSITE_SCORE" id="mznbSsWOOpk">
>                             <displayName>COMPOSITE_SCORE</displayName>
>                             <externalAccess>false</externalAccess>
>                             <userGroupAccesses/>
>                             <attributeValues/>
>                         </option>
>
> Then I checked that the path affecting attributeValues is the right one
> *Checking path to attributeValues is the right one by filtering that field
> out (it works)*:
> https://<>/api/optionSets?paging=false&fields=*,options[*
> ,!attributeValues]
>
> You get the same xml without the attributeValues entry.
>
> And finally try to the get the values associated to my options without any
> success..
>
> *Asking all from attributeValues in different manners*:
>
> https://<>/api/optionSets?paging=false&fields=*,options[*
> ,attributeValues[*]]
>
> https://<>/api/optionSets?paging=false&fields=*,options[*,attributeValues[
> *,attribute[*]]]
>
> https://<>/api/optionSets?paging=false&fields=*,options[*
> ,attributeValues[*,attribute[name,displayName,created,lastUpdated,access,id,valueType,code]]]
>
> https://<>/api/optionSets?paging=false&fields=*,options[*,option[
> *,attributeValues[*]]]
>
> None of these attempts return the info of the attributeValues, any clue?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dhis2/dhis2-android-sdk/issues/60>.
>



-- 
Morten
